### ISSUE TITLE
Add option to pass ViewData and ModelState to pug views

### ISSUE THREAD

**Issue by dpaquette** [AspNetMonsters/pugzor#10]

**Comment by stimms** [comment]
Right now we pass in simply the model. To get access to the viewstate we have a couple of options

1. Mix the viewstate and model with the model we pass into pugzor, verserving viewstate name, so if your model looked like 

   ```
   {
      "FirstName": "bill"
   }
   ```

   and your view state  like 

   ```
   {
     "Countries" : [ "Canada",...]
   }
   ```

   The result would be 

   ```
   {
      "FirstName": "bill",
      "ViewState": {
            "Countries" : [ "Canada",...]
       } 
   }
   ```

2. Mix the viewstate and model fields

   ```
   {
      "FirstName": "bill",
       "Countries" : [ "Canada",...]
   }
   ```

3. Push model data down a level

   ```
   {
      "Model": {
             "FirstName": "bill"}
      },
      "ViewState": {
            "Countries" : [ "Canada",...]
       } 
   }
   ```

Right now I'm leaning towards just doing #1.  It would be pretty weird for people to already have fields like ViewState and ModelState on their model. It seems an "okay" sort of limitation to have.

**Comment by dpaquette** [comment]
Yeah I also prefer #1



On Sun, Nov 20, 2016 at 1:31 PM -0700, "Simon Timms" <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now we pass in simply the model. To get access to the viewstate we have a couple of options

  1.  Mix the viewstate and model with the model we pass into pugzor, verserving viewstate name, so if your model looked like

{
  "FirstName": "bill"
}


and your view state like

{
 "Countries" : [ "Canada",...]
}


The result would be

{
  "FirstName": "bill",
  "ViewState": {
        "Countries" : [ "Canada",...]
   }
}


  2.  Mix the viewstate and model fields

{
  "FirstName": "bill",
   "Countries" : [ "Canada",...]
}


  3.  Push model data down a level

{
  "Model": {
         "FirstName": "bill"}
  },
  "ViewState": {
        "Countries" : [ "Canada",...]
   }
}


Right now I'm leaning towards just doing #1<https://github.com/AspNetMonsters/pugzor/pull/1>. It would be pretty weird for people to already have fields like ViewState and ModelState on their model. It seems an "okay" sort of limitation to have.

-
