### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by dpaquette** [AspNetMonsters/pugzor#15]
The initial version of pugzor was created during a 1 day hackathon. We did not create a unit test project but we should have one to test the PugzorViewEngine at a minimum.

**Comment by stimms** [comment]
Things the tests could cover which we don't currently

- [ ] Does view data get properly passed into pug?
- [ ] Does model state get properly passed into pug?
- [ ] Do the `MvcViewFeaturesMvcBuilderExtensions` do what they're supposed to?

**Comment by mavanmanen** [comment]
Can be closed.

**Comment by dpaquette** [comment]
Thanks @mavanmanen
