### ISSUE TITLE
Get this listed in the pug repo's readme file

### ISSUE THREAD

**Issue by dpaquette** [AspNetMonsters/pugzor#20]
The pug repo has a list of implementations in other languages. We should submit a PR to have pugzor added to the list.
https://github.com/pugjs/pug

**Comment by mavanmanen** [comment]
https://github.com/pugjs/pug/pull/2848 😉

**Comment by mavanmanen** [comment]
The repo got added, woohoo 🎉

**Comment by dpaquette** [comment]
Thanks @mavanmanen
