### ISSUE TITLE
pretty print option

### ISSUE THREAD

**Issue by snovak7** [AspNetMonsters/pugzor#22]
How can I do a pretty print?

Reference: http://stackoverflow.com/questions/5276892/how-to-output-pretty-html-in-express/11812841#11812841

**Comment by dpaquette** [comment]
We would need to add that option to the Pugzor config.

**Comment by mavanmanen** [comment]
Deprecated, thus should not be implemented as it will be removed in the future: https://pugjs.org/api/reference.html#options
